version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo
        network_mode: bridge
        ports:
            - 27017:27017
        volumes:
            - mongo-data-volume:/data/db
    postgres:
        container_name: postgres
        image: postgres
        network_mode: bridge
        ports:
            - 5432:5432
        volumes:
            - postgres-data-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
    pgadmin4:
        container_name: pgadmin4
        image: dpage/pgadmin4
        network_mode: bridge
        ports:
            - 80:80
        volumes:
            - pgadmin4:/var/lib/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres
            PGADMIN_DEFAULT_PASSWORD: postgres
volumes:
    postgres-data-volume:
        name: postgres-data
        driver: local
    mongo-data-volume:
        name: mongo-data
        driver: local
        